# This configuration does not include a processing node
# Which makes for faster setup times
version: '2'
volumes:
  appmedia:
    driver: local
services:
  db:
    image: opendronemap/webodm_db
    container_name: tradr-odm_db
    ports:
      - "5432"
    volumes:
      - "${MISSION_PATH}/db:/var/lib/postgresql/data"
  webapp:
    image: tradr/webodm_webapp
    container_name: tradr-odm_webapp
    entrypoint: /bin/bash -c "chmod +x /webodm/*.sh && /bin/bash -c \"/webodm/wait-for-it.sh db:5432 -- /webodm/start.sh\""
    volumes:
      - "${MISSION_PATH}/appmedia:/webodm/app/media"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - node-odm-1
    restart: on-failure:10
  node-odm-1:
    image: tradr/node-opendronemap
    container_name: node-odm-1
    ports:
      - "3000"

